######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       A GitHub Action to check whether an input value equals either
##              `'true'` or `'false'`.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        action.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

# The icon with which this Action is presented in the Marketplace.
branding:
  color: green
  icon: thumbs-up

# About this Action.
author: 'https://github.com/kevinmatthes'
description: |
  A GitHub Action to check whether an input value equals either `'true'` or
  `'false'`.
name: validate-boolean

# The information to be input.
inputs:
  check:
    description: The input to check.
    required: true

# The actual behaviour of this Action.
runs:
  using: composite
  steps:
    - if: inputs.check == 'false' || inputs.check == 'true'
      name: Check whether the input equals 'true' or 'false'.
      run: bash -c 'exit 0'
      shell: bash

    - if: failure ()
      name: The check failed.
      run: bash -c 'exit 64'
      shell: bash

################################################################################
